# 服务器配置
server:
  port: ${PORT:8082 }

# 数据库配置(MySQL)
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/user_manage?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  # 初始化数据
  sql:
    init:
      mode: always

  # Thymeleaf配置
  thymeleaf:
    cache: false
